enum ActionType {
    GET_USERS = 'GET_USERS',
    POST_USERS = 'POST_USERS',
    USERS_ERROR = 'USERS_ERROR',

    GET_EMPLOYEES_TIME_TODAY_START = 'GET_EMPLOYEES_TIME_TODAY_START',
    GET_EMPLOYEES_TIME_TODAY_SUCCESS = 'GET_EMPLOYEES_TIME_TODAY_SUCCESS',
    GET_EMPLOYEES_TIME_TODAY_ERROR = 'GET_EMPLOYEES_TIME_TODAY_ERROR',

    ///DashBoard////
    GET_SICK_LEAVE_TO_DAY = 'GET_SICK_LEAVE_TO_DAY',
    GET_OTHER_LEAVE_TODAY='GET_OTHER_LEAVE_TODAY',
    GET_ARRIVED = 'GET_ARRIVED',
    GET_COMMING ='GET_COMMING',
    GET_TOTAL_EMPLOYEES = 'GET_TOTAL_EMPLOYEES',
    GET_DASHBOARD_ERROR='GET_DASHBOARD_ERROR',

    ///OtherLeaves////
    GET_LEAVE ='GET_LEAVE',
    GET_LEAVE_TODAY ='GET_LEAVE_TODAY',
    GET_LEAVE_MONTH ='GET_LEAVE_MONTH',
    GET_LEAVE_30_DAY ='GET_LEAVE_30_DAY',
    GET_LEAVE_ERROR ='GET_LEAVE_ERROR',

    ///Post_Time_Employees////
    POST_TIME_TODAY_START = 'POST_TIME_TODAY_START',
    POST_TIME_TODAY_SUCCESS = 'POST_TIME_TODAY_SUCCESS',
    POST_TIME_TODAY_ERROR = 'POST_TIME_TODAY_ERROR',

    ///Put_Time_Employees////
    PUT_TIME_TODAY_START = 'PUT_TIME_TODAY_START',
    PUT_TIME_TODAY_SUCCESS = 'POST_TIME_TODAY_SUCCESS',
    PUT_TIME_TODAY_ERROR = 'POST_TIME_TODAY_ERROR',

    ///Export////
    GET_EXPORT ='GET_EXPROT_ATTENDACE',

    ///Summary of Employees///
    GET_SUMMARY_OF_EMPLOYEES='GET_SUMMARY_OF_EMPLOYEES',

    ///Summary of Work///
    GET_SUMMARY_OF_WORK='GET_SUMMARY_OF_WORK',






}

export interface IAction<T> {
    type: ActionType;
    payload: T;
}


export default ActionType